server:
  port: 30200

# spring 配置
spring:
  application:
    name: alinesno-infra-data-mdm-boot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dev_alinesno_infra_data_mdm_v100?characterEncoding=UTF-8&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: Qax@168
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  devtools:
    restart:
      enabled: true